name: Pylint

on: [push]

jobs:
        check-job:
                runs-on: ubuntu-latest
                steps: 
                        - name: check-step
                          run:
                                pip install poetry
                                make lint
